import type { AnimeItem, AnimeStatus, AnimeType, SeasonName } from "./types";

export const ANIME_GENRES = [
  "Action",
  "Adventure",
  "Comedy",
  "Drama",
  "Fantasy",
  "Isekai",
  "Mecha",
  "Mystery",
  "Psychological",
  "Romance",
  "Sci-Fi",
  "Slice of Life",
  "Sports",
  "Supernatural",
  "Thriller",
];

export const ANIME_STATUSES: AnimeStatus[] = [
  "Airing",
  "Finished",
  "Upcoming",
  "Draft",
];

export const ANIME_TYPES: AnimeType[] = ["TV", "Movie", "OVA", "Special", "ONA"];

export const ANIME_SEASONS: SeasonName[] = ["Winter", "Spring", "Summer", "Fall"];

export const MOCK_ANIME_DATA: AnimeItem[] = [
  {
    id: "ani-1",
    titleRomaji: "Shingeki no Kyojin: The Final Season",
    titleEnglish: "Attack on Titan Final Season",
    titleJapanese: "進撃の巨人 The Final Season",
    slug: "attack-on-titan-final-season",
    coverImage: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&q=80",
    bannerImage: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1200&q=80",
    synopsis: "Gabi Braun and Falco Grice have been training their entire lives to inherit one of the seven Titans under Marley's control and aid their nation in eradicating the Eldians on Paradis.",
    type: "TV",
    status: "Finished",
    episodes: 28,
    durationPerEp: "24m",
    season: { year: 2022, season: "Winter" },
    rating: 9.05,
    studios: ["MAPPA"],
    genres: ["Action", "Drama", "Fantasy", "Mystery"],
    featured: true,
    trending: true,
    createdAt: "2026-01-15T08:00:00Z",
    updatedAt: "2026-08-20T14:30:00Z",
  },
  {
    id: "ani-2",
    titleRomaji: "Jujutsu Kaisen 2nd Season",
    titleEnglish: "Jujutsu Kaisen Season 2",
    titleJapanese: "呪術廻戦 第2期",
    slug: "jujutsu-kaisen-season-2",
    coverImage: "https://images.unsplash.com/photo-1563089145-599997674d42?w=400&q=80",
    bannerImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&q=80",
    synopsis: "The past comes back to haunt Satoru Gojo and Suguru Geto in their high school years, detailing the Kaidai Incident and Shibuya Incident.",
    type: "TV",
    status: "Finished",
    episodes: 23,
    durationPerEp: "24m",
    season: { year: 2023, season: "Summer" },
    rating: 8.82,
    studios: ["MAPPA"],
    genres: ["Action", "Supernatural", "Fantasy"],
    featured: true,
    trending: true,
    createdAt: "2026-02-10T10:00:00Z",
    updatedAt: "2026-08-24T09:15:00Z",
  },
  {
    id: "ani-3",
    titleRomaji: "Sousou no Frieren",
    titleEnglish: "Frieren: Beyond Journey's End",
    titleJapanese: "葬送のフリーレン",
    slug: "frieren-beyond-journeys-end",
    coverImage: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&q=80",
    bannerImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&q=80",
    synopsis: "Elven mage Frieren and her courageous fellow adventurers have defeated the Demon King and brought peace to the land. But Frieren will long outlive her former comrades.",
    type: "TV",
    status: "Airing",
    episodes: 28,
    durationPerEp: "24m",
    season: { year: 2023, season: "Fall" },
    rating: 9.34,
    studios: ["Madhouse"],
    genres: ["Adventure", "Drama", "Fantasy"],
    featured: true,
    trending: true,
    createdAt: "2026-03-01T12:00:00Z",
    updatedAt: "2026-08-25T11:00:00Z",
  },
  {
    id: "ani-4",
    titleRomaji: "Kimetsu no Yaiba: Hashira Geiko-hen",
    titleEnglish: "Demon Slayer: Hashira Training Arc",
    titleJapanese: "鬼滅の刃 柱稽古編",
    slug: "demon-slayer-hashira-training-arc",
    coverImage: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=400&q=80",
    bannerImage: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1200&q=80",
    synopsis: "Tanjiro goes to see the Stone Hashira, Himejima, who intends to prepare him for the upcoming battles against Kibutsuji Muzan.",
    type: "TV",
    status: "Finished",
    episodes: 8,
    durationPerEp: "24m",
    season: { year: 2024, season: "Spring" },
    rating: 8.55,
    studios: ["ufotable"],
    genres: ["Action", "Fantasy", "Supernatural"],
    featured: false,
    trending: true,
    createdAt: "2026-04-12T09:30:00Z",
    updatedAt: "2026-08-18T16:20:00Z",
  },
  {
    id: "ani-5",
    titleRomaji: "Solo Leveling: Arise",
    titleEnglish: "Solo Leveling Season 2",
    titleJapanese: "俺だけレベルアップな件",
    slug: "solo-leveling-season-2",
    coverImage: "https://images.unsplash.com/photo-1614036417651-efe5912149d8?w=400&q=80",
    bannerImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&q=80",
    synopsis: "Sung Jinwoo continues his quest to uncover the secret behind the System and the Monarchs while protecting humanity.",
    type: "TV",
    status: "Upcoming",
    episodes: 12,
    durationPerEp: "24m",
    season: { year: 2025, season: "Winter" },
    rating: 8.70,
    studios: ["A-1 Pictures"],
    genres: ["Action", "Fantasy", "Isekai"],
    featured: false,
    trending: false,
    createdAt: "2026-06-01T15:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
  },
  {
    id: "ani-6",
    titleRomaji: "Kimi no Na wa.",
    titleEnglish: "Your Name.",
    titleJapanese: "君の名は。",
    slug: "your-name",
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&q=80",
    bannerImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    synopsis: "Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?",
    type: "Movie",
    status: "Finished",
    episodes: 1,
    durationPerEp: "1m 46s",
    season: { year: 2016, season: "Summer" },
    rating: 8.95,
    studios: ["CoMix Wave Films"],
    genres: ["Romance", "Drama", "Supernatural"],
    featured: true,
    trending: false,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-07-12T13:45:00Z",
  },
];
