import type {
  UserProfile,
  WatchlistItem,
  WatchHistoryItem,
  UserSettings,
} from "@/types/user";
import { FEATURED_ANIME, TRENDING_ANIME, EXTRA_ANIME } from "@/lib/mock-anime";

export const MOCK_USER_PROFILE: UserProfile = {
  id: "user-99182",
  username: "otakuking",
  displayName: "Alex Vance",
  email: "alex.vance@goxstream.com",
  avatarUrl:
    "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
  bannerUrl: "linear-gradient(135deg, #1e1b4b 0%, #312e81 40%, #0f172a 100%)",
  bio: "Passionate anime collector & simulcast watcher. Shounen and Dark Fantasy enthusiast. ⚡",
  joinDate: "January 2024",
  isVip: true,
  vipTier: "Ultra Streamer",
  stats: {
    animeCompleted: 142,
    episodesWatched: 2840,
    hoursWatched: 1136,
    watchlistCount: 18,
    favoriteGenres: [
      { genre: "Action", percentage: 38 },
      { genre: "Fantasy", percentage: 26 },
      { genre: "Supernatural", percentage: 18 },
      { genre: "Comedy", percentage: 12 },
      { genre: "Drama", percentage: 6 },
    ],
  },
};

export const MOCK_WATCHLIST: WatchlistItem[] = [
  {
    id: "wl-1",
    anime: FEATURED_ANIME,
    status: "watching",
    isFavorite: true,
    currentEpisode: 12,
    totalEpisodes: 24,
    rating: 5,
    updatedAt: "2 hours ago",
  },
  {
    id: "wl-2",
    anime: TRENDING_ANIME[0],
    status: "watching",
    isFavorite: true,
    currentEpisode: 7,
    totalEpisodes: 12,
    rating: 5,
    updatedAt: "Yesterday",
  },
  {
    id: "wl-3",
    anime: TRENDING_ANIME[1],
    status: "watching",
    isFavorite: false,
    currentEpisode: 14,
    totalEpisodes: 24,
    rating: 4.5,
    updatedAt: "3 days ago",
  },
  {
    id: "wl-4",
    anime: TRENDING_ANIME[3],
    status: "plan_to_watch",
    isFavorite: false,
    currentEpisode: 0,
    totalEpisodes: 24,
    updatedAt: "1 week ago",
  },
  {
    id: "wl-5",
    anime: EXTRA_ANIME[0],
    status: "completed",
    isFavorite: true,
    currentEpisode: 13,
    totalEpisodes: 13,
    rating: 5,
    updatedAt: "2 weeks ago",
  },
  {
    id: "wl-6",
    anime: EXTRA_ANIME[1],
    status: "completed",
    isFavorite: true,
    currentEpisode: 1,
    totalEpisodes: 1,
    rating: 5,
    updatedAt: "1 month ago",
  },
  {
    id: "wl-7",
    anime: EXTRA_ANIME[3],
    status: "plan_to_watch",
    isFavorite: false,
    currentEpisode: 0,
    totalEpisodes: 24,
    updatedAt: "3 weeks ago",
  },
];

export const MOCK_WATCH_HISTORY: WatchHistoryItem[] = [
  {
    id: "hist-1",
    animeId: FEATURED_ANIME.id,
    animeSlug: FEATURED_ANIME.slug,
    animeTitle: FEATURED_ANIME.title,
    animeCover: FEATURED_ANIME.coverImage,
    episodeNumber: 14,
    episodeTitle: "The Sovereign's Command",
    progressPercent: 78,
    durationSeconds: 1440,
    watchedSeconds: 1123,
    lastWatchedAt: "15 minutes ago",
  },
  {
    id: "hist-2",
    animeId: TRENDING_ANIME[0].id,
    animeSlug: TRENDING_ANIME[0].slug,
    animeTitle: TRENDING_ANIME[0].title,
    animeCover: TRENDING_ANIME[0].coverImage,
    episodeNumber: 8,
    episodeTitle: "Upper Rank Three: Akaza",
    progressPercent: 100,
    durationSeconds: 1560,
    watchedSeconds: 1560,
    lastWatchedAt: "2 hours ago",
  },
  {
    id: "hist-3",
    animeId: TRENDING_ANIME[1].id,
    animeSlug: TRENDING_ANIME[1].slug,
    animeTitle: TRENDING_ANIME[1].title,
    animeCover: TRENDING_ANIME[1].coverImage,
    episodeNumber: 17,
    episodeTitle: "Tokyo No. 1 Colony",
    progressPercent: 45,
    durationSeconds: 1440,
    watchedSeconds: 648,
    lastWatchedAt: "Yesterday",
  },
  {
    id: "hist-4",
    animeId: TRENDING_ANIME[2].id,
    animeSlug: TRENDING_ANIME[2].slug,
    animeTitle: TRENDING_ANIME[2].title,
    animeCover: TRENDING_ANIME[2].coverImage,
    episodeNumber: 1,
    episodeTitle: "Reze the Bomb Girl",
    progressPercent: 100,
    durationSeconds: 6900,
    watchedSeconds: 6900,
    lastWatchedAt: "3 days ago",
  },
  {
    id: "hist-5",
    animeId: EXTRA_ANIME[0].id,
    animeSlug: EXTRA_ANIME[0].slug,
    animeTitle: EXTRA_ANIME[0].title,
    animeCover: EXTRA_ANIME[0].coverImage,
    episodeNumber: 13,
    episodeTitle: "The Conflict Final Chapter",
    progressPercent: 100,
    durationSeconds: 1500,
    watchedSeconds: 1500,
    lastWatchedAt: "5 days ago",
  },
];

export const MOCK_USER_SETTINGS: UserSettings = {
  profile: {
    displayName: "Alex Vance",
    bio: "Passionate anime collector & simulcast watcher. Shounen and Dark Fantasy enthusiast. ⚡",
    avatarUrl:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
  },
  player: {
    defaultQuality: "1080p",
    defaultSubtitle: "id",
    autoPlayNext: true,
    autoSkipIntro: true,
    preferredAudio: "subbed",
  },
  notifications: {
    newEpisodeAlerts: true,
    watchlistUpdates: true,
    marketingEmails: false,
    publicWatchlist: true,
  },
};
