import type { DayOfWeek, ScheduleItem } from '@/types/schedule';
import { DAYS_OF_WEEK_MAP } from '@/lib/constants';

export const MOCK_SCHEDULE_ITEMS: ScheduleItem[] = [
  // --- MONDAY ---
  {
    id: "sch-mon-1",
    animeId: "anime-10",
    slug: "solo-leveling-season-2",
    title: "Solo Leveling: Arise from the Shadows",
    japaneseTitle: "俺だけレベルアップな件",
    coverImage: "linear-gradient(135deg, #0f172a 0%, #1e1b4b 50%, #312e81 100%)",
    airDay: "monday",
    airTime: "17:30",
    episodeNumber: 15,
    status: "aired",
    genres: ["Action", "Fantasy", "Supernatural"],
    rating: 4.9,
    studio: "A-1 Pictures",
    subOrDub: "SUB & DUB",
    season: "Winter",
    year: 2026,
    isPopular: true,
  },
  {
    id: "sch-mon-2",
    animeId: "anime-11",
    slug: "classroom-of-the-elite-s4",
    title: "Classroom of the Elite Season 4",
    japaneseTitle: "ようこそ実力至上主義の教室へ 4th Season",
    coverImage: "linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #4338ca 100%)",
    airDay: "monday",
    airTime: "20:00",
    episodeNumber: 8,
    status: "aired",
    genres: ["Drama", "Psychological", "School"],
    rating: 4.75,
    studio: "Lerche",
    subOrDub: "SUB",
    season: "Winter",
    year: 2026,
  },
  {
    id: "sch-mon-3",
    animeId: "anime-12",
    slug: "tsukimichi-moonlit-fantasy-s3",
    title: "Tsukimichi: Moonlit Fantasy Season 3",
    japaneseTitle: "月が導く異世界道中 第三幕",
    coverImage: "linear-gradient(135deg, #0284c7 0%, #0369a1 50%, #075985 100%)",
    airDay: "monday",
    airTime: "22:30",
    episodeNumber: 10,
    status: "aired",
    genres: ["Isekai", "Action", "Comedy", "Fantasy"],
    rating: 4.6,
    studio: "J.C.Staff",
    subOrDub: "SUB & DUB",
    season: "Winter",
    year: 2026,
  },

  // --- TUESDAY ---
  {
    id: "sch-tue-1",
    animeId: "anime-13",
    slug: "black-clover-s5",
    title: "Black Clover: Spade Kingdom Arc Part 2",
    japaneseTitle: "ブラッククローバー",
    coverImage: "linear-gradient(135deg, #27272a 0%, #3f3f46 50%, #52525b 100%)",
    airDay: "tuesday",
    airTime: "18:00",
    episodeNumber: 178,
    status: "aired",
    genres: ["Action", "Magic", "Shounen"],
    rating: 4.82,
    studio: "Studio Pierrot",
    subOrDub: "SUB & DUB",
    season: "Winter",
    year: 2026,
    isPopular: true,
  },
  {
    id: "sch-tue-2",
    animeId: "anime-14",
    slug: "blue-lock-vs-u20-japan",
    title: "Blue Lock: U-20 Japan Match Arc",
    japaneseTitle: "ブルーロック vs. U-20 JAPAN",
    coverImage: "linear-gradient(135deg, #1e3a8a 0%, #1d4ed8 50%, #2563eb 100%)",
    airDay: "tuesday",
    airTime: "21:00",
    episodeNumber: 12,
    status: "aired",
    genres: ["Sports", "Shounen", "Drama"],
    rating: 4.87,
    studio: "Eight Bit",
    subOrDub: "SUB & DUB",
    season: "Winter",
    year: 2026,
    isPopular: true,
  },

  // --- WEDNESDAY ---
  {
    id: "sch-wed-1",
    animeId: "anime-1",
    slug: "demon-slayer-infinity-castle",
    title: "Demon Slayer: Infinity Castle Arc",
    japaneseTitle: "鬼滅の刃 無限城編",
    coverImage: "linear-gradient(135deg, #18181b 0%, #3f3f46 50%, #15803d 100%)",
    airDay: "wednesday",
    airTime: "18:30",
    episodeNumber: 9,
    status: "airing_now",
    countdownText: "Airing live now!",
    genres: ["Action", "Demons", "Historical"],
    rating: 4.95,
    studio: "ufotable",
    subOrDub: "SUB & DUB",
    season: "Winter",
    year: 2026,
    isPopular: true,
  },
  {
    id: "sch-wed-2",
    animeId: "anime-15",
    slug: "dr-stone-science-future",
    title: "Dr. STONE: Science Future",
    japaneseTitle: "ドクターストーン SCIENCE FUTURE",
    coverImage: "linear-gradient(135deg, #14532d 0%, #15803d 50%, #16a34a 100%)",
    airDay: "wednesday",
    airTime: "20:30",
    episodeNumber: 7,
    status: "upcoming",
    countdownText: "In 1h 20m",
    genres: ["Sci-Fi", "Adventure", "Comedy"],
    rating: 4.81,
    studio: "TMS Entertainment",
    subOrDub: "SUB & DUB",
    season: "Winter",
    year: 2026,
  },
  {
    id: "sch-wed-3",
    animeId: "anime-16",
    slug: "re-zero-season-3-part-2",
    title: "Re:ZERO -Starting Life in Another World- S3",
    japaneseTitle: "Re:ゼロから始める異世界生活 3rd Season",
    coverImage: "linear-gradient(135deg, #581c87 0%, #7e22ce 50%, #9333ea 100%)",
    airDay: "wednesday",
    airTime: "23:00",
    episodeNumber: 14,
    status: "upcoming",
    countdownText: "In 3h 50m",
    genres: ["Psychological", "Isekai", "Drama", "Fantasy"],
    rating: 4.89,
    studio: "White Fox",
    subOrDub: "SUB & DUB",
    season: "Winter",
    year: 2026,
    isPopular: true,
  },

  // --- THURSDAY ---
  {
    id: "sch-thu-1",
    animeId: "anime-2",
    slug: "jujutsu-kaisen-culling-game",
    title: "Jujutsu Kaisen: Culling Game",
    japaneseTitle: "呪術廻戦 死滅回游",
    coverImage: "linear-gradient(135deg, #09090b 0%, #1c1917 50%, #991b1b 100%)",
    airDay: "thursday",
    airTime: "17:00",
    episodeNumber: 19,
    status: "upcoming",
    countdownText: "Tomorrow at 17:00",
    genres: ["Action", "Supernatural", "Dark Fantasy"],
    rating: 4.88,
    studio: "MAPPA",
    subOrDub: "SUB & DUB",
    season: "Winter",
    year: 2026,
    isPopular: true,
  },
  {
    id: "sch-thu-2",
    animeId: "anime-17",
    slug: "wind-breaker-season-2",
    title: "WIND BREAKER Season 2",
    japaneseTitle: "ウィンドブレイカー Season 2",
    coverImage: "linear-gradient(135deg, #065f46 0%, #047857 50%, #10b981 100%)",
    airDay: "thursday",
    airTime: "19:30",
    episodeNumber: 5,
    status: "upcoming",
    countdownText: "Tomorrow at 19:30",
    genres: ["Action", "Delinquents", "School"],
    rating: 4.72,
    studio: "CloverWorks",
    subOrDub: "SUB",
    season: "Winter",
    year: 2026,
  },
  {
    id: "sch-thu-3",
    animeId: "anime-18",
    slug: "dandadan-season-2",
    title: "Dandadan Season 2",
    japaneseTitle: "ダンダダン 2nd Season",
    coverImage: "linear-gradient(135deg, #9f1239 0%, #be123c 50%, #e11d48 100%)",
    airDay: "thursday",
    airTime: "22:00",
    episodeNumber: 4,
    status: "upcoming",
    countdownText: "Tomorrow at 22:00",
    genres: ["Action", "Comedy", "Supernatural", "Sci-Fi"],
    rating: 4.91,
    studio: "Science SARU",
    subOrDub: "SUB & DUB",
    season: "Winter",
    year: 2026,
    isPopular: true,
  },

  // --- FRIDAY ---
  {
    id: "sch-fri-1",
    animeId: "anime-4",
    slug: "frieren-beyond-journeys-end-s2",
    title: "Frieren: Beyond Journey's End S2",
    japaneseTitle: "葬送のフリーレン",
    coverImage: "linear-gradient(135deg, #064e3b 0%, #047857 50%, #0d9488 100%)",
    airDay: "friday",
    airTime: "18:00",
    episodeNumber: 7,
    status: "upcoming",
    countdownText: "Friday at 18:00",
    genres: ["Adventure", "Fantasy", "Drama"],
    rating: 4.97,
    studio: "Madhouse",
    subOrDub: "SUB & DUB",
    season: "Winter",
    year: 2026,
    isPopular: true,
  },
  {
    id: "sch-fri-2",
    animeId: "anime-19",
    slug: "bleach-thousand-year-blood-war-part-4",
    title: "Bleach: Thousand-Year Blood War - The Conflict",
    japaneseTitle: "BLEACH 千年血戦篇-相剋譚-",
    coverImage: "linear-gradient(135deg, #451a03 0%, #78350f 50%, #b45309 100%)",
    airDay: "friday",
    airTime: "20:30",
    episodeNumber: 38,
    status: "upcoming",
    countdownText: "Friday at 20:30",
    genres: ["Action", "Supernatural", "Shounen"],
    rating: 4.93,
    studio: "Studio Pierrot",
    subOrDub: "SUB & DUB",
    season: "Winter",
    year: 2026,
    isPopular: true,
  },

  // --- SATURDAY ---
  {
    id: "sch-sat-1",
    animeId: "anime-5",
    slug: "kaiju-no-8-season-2",
    title: "Kaiju No. 8 Season 2",
    japaneseTitle: "怪獣8号 2nd Season",
    coverImage: "linear-gradient(135deg, #111827 0%, #1f2937 50%, #115e59 100%)",
    airDay: "saturday",
    airTime: "17:30",
    episodeNumber: 3,
    status: "upcoming",
    countdownText: "Saturday at 17:30",
    genres: ["Action", "Sci-Fi", "Military"],
    rating: 4.84,
    studio: "Production I.G",
    subOrDub: "SUB & DUB",
    season: "Winter",
    year: 2026,
    isPopular: true,
  },
  {
    id: "sch-sat-2",
    animeId: "anime-20",
    slug: "my-hero-academia-final-season",
    title: "My Hero Academia: The Final Battle",
    japaneseTitle: "僕のヒーローアカデミア FINAL",
    coverImage: "linear-gradient(135deg, #854d0e 0%, #a16207 50%, #ca8a04 100%)",
    airDay: "saturday",
    airTime: "19:00",
    episodeNumber: 160,
    status: "upcoming",
    countdownText: "Saturday at 19:00",
    genres: ["Action", "Super Power", "Shounen"],
    rating: 4.86,
    studio: "Bones",
    subOrDub: "SUB & DUB",
    season: "Winter",
    year: 2026,
    isPopular: true,
  },

  // --- SUNDAY ---
  {
    id: "sch-sun-1",
    animeId: "anime-21",
    slug: "one-piece-elbaf-arc",
    title: "One Piece: Elbaf Island Arc",
    japaneseTitle: "ONE PIECE エルバフ編",
    coverImage: "linear-gradient(135deg, #1e3a8a 0%, #0369a1 50%, #0284c7 100%)",
    airDay: "sunday",
    airTime: "09:30",
    episodeNumber: 1125,
    status: "upcoming",
    countdownText: "Sunday at 09:30",
    genres: ["Action", "Adventure", "Fantasy"],
    rating: 4.96,
    studio: "Toei Animation",
    subOrDub: "SUB & DUB",
    season: "Winter",
    year: 2026,
    isPopular: true,
  },
  {
    id: "sch-sun-2",
    animeId: "anime-22",
    slug: "mushoku-tensei-season-3",
    title: "Mushoku Tensei: Jobless Reincarnation S3",
    japaneseTitle: "無職転生 III ～異世界行ったら本気だす～",
    coverImage: "linear-gradient(135deg, #365314 0%, #4d7c0f 50%, #65a30d 100%)",
    airDay: "sunday",
    airTime: "21:30",
    episodeNumber: 2,
    status: "upcoming",
    countdownText: "Sunday at 21:30",
    genres: ["Isekai", "Drama", "Fantasy", "Magic"],
    rating: 4.89,
    studio: "Studio Bind",
    subOrDub: "SUB & DUB",
    season: "Winter",
    year: 2026,
    isPopular: true,
  },
];

/**
 * Utility function to get current day of week
 */
export function getCurrentDayOfWeek(): DayOfWeek {
  const dayIndex = new Date().getDay();
  const dayMap: Record<number, DayOfWeek> = {
    0: 'sunday',
    1: 'monday',
    2: 'tuesday',
    3: 'wednesday',
    4: 'thursday',
    5: 'friday',
    6: 'saturday',
  };
  return dayMap[dayIndex] || 'wednesday';
}

/**
 * Filter schedule items by Day of Week and optional search query
 */
export function getScheduleByDay(
  day: DayOfWeek,
  searchQuery = ''
): ScheduleItem[] {
  let items = MOCK_SCHEDULE_ITEMS.filter((item) => item.airDay === day);

  if (searchQuery.trim()) {
    const q = searchQuery.toLowerCase().trim();
    items = items.filter(
      (item) =>
        item.title.toLowerCase().includes(q) ||
        (item.japaneseTitle && item.japaneseTitle.toLowerCase().includes(q)) ||
        item.genres.some((g) => g.toLowerCase().includes(q)) ||
        item.studio.toLowerCase().includes(q)
    );
  }

  return items.sort((a, b) => a.airTime.localeCompare(b.airTime));
}
