import type { AnimeItem, EpisodeItem, PlatformStat } from "@/types/anime";

// High-fidelity SVG card placeholders with custom visual themes
export const FEATURED_ANIME: AnimeItem = {
  id: "featured-1",
  slug: "solo-leveling-season-2",
  title: "Solo Leveling: Arise from the Shadows",
  japaneseTitle: "俺だけレベルアップな件",
  synopsis:
    "When a gate connecting our world to a dimension of monsters appeared, Sung Jin-woo gained the ability to level up infinitely. Now facing monarch-level threats, humanity's weakest hunter becomes the Shadow Monarch.",
  coverImage: "linear-gradient(135deg, #0f172a 0%, #1e1b4b 50%, #312e81 100%)",
  bannerImage: "linear-gradient(135deg, #020617 0%, #0f172a 40%, #1e1b4b 100%)",
  rating: 4.9,
  episodesCount: 24,
  latestEpisode: 14,
  status: "Ongoing",
  type: "TV",
  season: "Winter",
  year: 2026,
  genres: ["Action", "Fantasy", "Supernatural", "Adventure"],
  studio: "A-1 Pictures",
  isTrending: true,
  isFeatured: true,
  subOrDub: "SUB & DUB",
};

export const TRENDING_ANIME: AnimeItem[] = [
  {
    id: "anime-1",
    slug: "demon-slayer-infinity-castle",
    title: "Demon Slayer: Infinity Castle Arc",
    japaneseTitle: "鬼滅の刃 無限城編",
    synopsis: "The Demon Slayer Corps plunges into the Infinity Castle to confront Muzan Kibutsuji and the remaining Upper Ranks in the final battle.",
    coverImage: "linear-gradient(135deg, #18181b 0%, #3f3f46 50%, #15803d 100%)",
    rating: 4.95,
    episodesCount: 12,
    latestEpisode: 8,
    status: "Ongoing",
    type: "TV",
    season: "Summer",
    year: 2026,
    genres: ["Action", "Demons", "Historical", "Shounen"],
    studio: "ufotable",
    isTrending: true,
    subOrDub: "SUB & DUB",
  },
  {
    id: "anime-2",
    slug: "jujutsu-kaisen-culling-game",
    title: "Jujutsu Kaisen: Culling Game",
    japaneseTitle: "呪術廻戦 死滅回游",
    synopsis: "Sorcerers and ancient resurrected curse users collide in a battle royale orchestrated by Kenjaku across Japan.",
    coverImage: "linear-gradient(135deg, #09090b 0%, #1c1917 50%, #991b1b 100%)",
    rating: 4.88,
    episodesCount: 24,
    latestEpisode: 18,
    status: "Ongoing",
    type: "TV",
    season: "Winter",
    year: 2026,
    genres: ["Action", "Supernatural", "Dark Fantasy"],
    studio: "MAPPA",
    isTrending: true,
    subOrDub: "SUB & DUB",
  },
  {
    id: "anime-3",
    slug: "chainsaw-man-reze-arc",
    title: "Chainsaw Man: Reze Arc",
    japaneseTitle: "チェンソーマン レゼ編",
    synopsis: "Denji encounters Reze, a mystery girl working at a coffee shop, unaware of her explosive true identity.",
    coverImage: "linear-gradient(135deg, #18181b 0%, #713f12 50%, #ea580c 100%)",
    rating: 4.91,
    episodesCount: 1,
    latestEpisode: 1,
    status: "Completed",
    type: "Movie",
    season: "Spring",
    year: 2026,
    genres: ["Action", "Dark Fantasy", "Horror"],
    studio: "MAPPA",
    isTrending: true,
    subOrDub: "SUB & DUB",
  },
  {
    id: "anime-4",
    slug: "frieren-beyond-journeys-end-s2",
    title: "Frieren: Beyond Journey's End S2",
    japaneseTitle: "葬送のフリーレン",
    synopsis: "Elven mage Frieren continues her journey north to Ende, learning what it truly means to connect with humans along the way.",
    coverImage: "linear-gradient(135deg, #064e3b 0%, #047857 50%, #0d9488 100%)",
    rating: 4.97,
    episodesCount: 24,
    latestEpisode: 6,
    status: "Ongoing",
    type: "TV",
    season: "Winter",
    year: 2026,
    genres: ["Adventure", "Drama", "Fantasy"],
    studio: "Madhouse",
    isTrending: true,
    subOrDub: "SUB",
  },
  {
    id: "anime-5",
    slug: "spy-x-family-season-3",
    title: "SPY x FAMILY Season 3",
    japaneseTitle: "スパイファミリー",
    synopsis: "Spy Twilight, assassin Yor, and telepathic Anya balance secret covert missions with suburban family life.",
    coverImage: "linear-gradient(135deg, #1e293b 0%, #334155 50%, #0284c7 100%)",
    rating: 4.82,
    episodesCount: 12,
    latestEpisode: 10,
    status: "Ongoing",
    type: "TV",
    season: "Autumn",
    year: 2026,
    genres: ["Comedy", "Action", "Slice of Life"],
    studio: "CloverWorks x WIT",
    isTrending: true,
    subOrDub: "SUB & DUB",
  },
];

export const LATEST_EPISODES: EpisodeItem[] = [
  {
    id: "ep-101",
    animeId: "featured-1",
    animeSlug: "solo-leveling-season-2",
    animeTitle: "Solo Leveling: Arise from the Shadows",
    episodeNumber: 14,
    episodeTitle: "The Sovereign's Command",
    thumbnail: "linear-gradient(135deg, #0f172a 0%, #312e81 100%)",
    duration: "24m",
    releasedAt: "12 minutes ago",
    isSub: true,
    isDub: true,
  },
  {
    id: "ep-102",
    animeId: "anime-1",
    animeSlug: "demon-slayer-infinity-castle",
    animeTitle: "Demon Slayer: Infinity Castle Arc",
    episodeNumber: 8,
    episodeTitle: "Upper Rank Three: Akaza",
    thumbnail: "linear-gradient(135deg, #18181b 0%, #15803d 100%)",
    duration: "26m",
    releasedAt: "45 minutes ago",
    isSub: true,
    isDub: false,
  },
  {
    id: "ep-103",
    animeId: "anime-4",
    animeSlug: "frieren-beyond-journeys-end-s2",
    animeTitle: "Frieren: Beyond Journey's End S2",
    episodeNumber: 6,
    episodeTitle: "The Northern Frontier",
    thumbnail: "linear-gradient(135deg, #064e3b 0%, #0d9488 100%)",
    duration: "23m",
    releasedAt: "2 hours ago",
    isSub: true,
    isDub: true,
  },
  {
    id: "ep-104",
    animeId: "anime-2",
    animeSlug: "jujutsu-kaisen-culling-game",
    animeTitle: "Jujutsu Kaisen: Culling Game",
    episodeNumber: 18,
    episodeTitle: "Tokyo No. 1 Colony",
    thumbnail: "linear-gradient(135deg, #1c1917 0%, #991b1b 100%)",
    duration: "24m",
    releasedAt: "3 hours ago",
    isSub: true,
    isDub: true,
  },
  {
    id: "ep-105",
    animeId: "anime-5",
    animeSlug: "spy-x-family-season-3",
    animeTitle: "SPY x FAMILY Season 3",
    episodeNumber: 10,
    episodeTitle: "Anya's Secret Operation",
    thumbnail: "linear-gradient(135deg, #1e293b 0%, #0284c7 100%)",
    duration: "22m",
    releasedAt: "5 hours ago",
    isSub: true,
    isDub: true,
  },
];

export const GENRES_LIST = [
  "All",
  "Action",
  "Adventure",
  "Fantasy",
  "Sci-Fi",
  "Romance",
  "Comedy",
  "Supernatural",
  "Dark Fantasy",
];

export const PLATFORM_STATS: PlatformStat[] = [
  {
    label: "Simulcast Speed",
    value: "< 5 Min",
    description: "Available minutes after official Japanese broadcast",
  },
  {
    label: "Video Fidelity",
    value: "1080p / 4K",
    description: "High bitrate, 60fps unlocked streaming",
  },
  {
    label: "Ad-Free",
    value: "100%",
    description: "Zero popups, video ads, or forced interruptions",
  },
  {
    label: "Active Anime",
    value: "10,000+",
    description: "Full library of subbed & dubbed series and films",
  },
];
