import type { CategoryItem, GenreItem } from "./types";

export const MOCK_CATEGORIES: CategoryItem[] = [
  {
    id: "cat-1",
    code: "TV",
    name: "TV Series",
    slug: "tv-series",
    animeCount: 842,
    description: "Standard television series broadcasted in episode format.",
    isActive: true,
    updatedAt: "2026-08-20T10:00:00Z",
  },
  {
    id: "cat-2",
    code: "MOVIE",
    name: "Anime Movies",
    slug: "anime-movies",
    animeCount: 186,
    description: "Feature-length theatrical release animation films.",
    isActive: true,
    updatedAt: "2026-08-18T14:30:00Z",
  },
  {
    id: "cat-3",
    code: "OVA",
    name: "Original Video Animation",
    slug: "ova",
    animeCount: 94,
    description: "Anime releases directly distributed to home media format.",
    isActive: true,
    updatedAt: "2026-07-30T08:15:00Z",
  },
  {
    id: "cat-4",
    code: "ONA",
    name: "Original Net Animation",
    slug: "ona",
    animeCount: 78,
    description: "Web-streamed series directly released online.",
    isActive: true,
    updatedAt: "2026-08-22T09:40:00Z",
  },
  {
    id: "cat-5",
    code: "SPECIAL",
    name: "Specials & Side Stories",
    slug: "specials",
    animeCount: 35,
    description: "Short bonus episodes, TV specials, and side stories.",
    isActive: true,
    updatedAt: "2026-06-12T11:00:00Z",
  },
  {
    id: "cat-6",
    code: "MUSIC",
    name: "Music Videos",
    slug: "music-videos",
    animeCount: 13,
    description: "Short animated music videos and idol promotional clips.",
    isActive: true,
    updatedAt: "2026-05-04T16:20:00Z",
  },
];

export const MOCK_GENRES: GenreItem[] = [
  {
    id: "gen-1",
    name: "Action",
    slug: "action",
    group: "Main Genre",
    animeCount: 654,
    description: "Fast-paced stories with physical conflicts, battles, and martial arts.",
    colorBadge: "default",
    isActive: true,
  },
  {
    id: "gen-2",
    name: "Adventure",
    slug: "adventure",
    group: "Main Genre",
    animeCount: 512,
    description: "Journeys, quests, and explorations in new worlds.",
    colorBadge: "secondary",
    isActive: true,
  },
  {
    id: "gen-3",
    name: "Comedy",
    slug: "comedy",
    group: "Main Genre",
    animeCount: 489,
    description: "Humorous situations, satire, and lighthearted entertainment.",
    colorBadge: "outline",
    isActive: true,
  },
  {
    id: "gen-4",
    name: "Fantasy",
    slug: "fantasy",
    group: "Main Genre",
    animeCount: 578,
    description: "Magic, mythical creatures, and otherworldly magic systems.",
    colorBadge: "default",
    isActive: true,
  },
  {
    id: "gen-5",
    name: "Sci-Fi",
    slug: "sci-fi",
    group: "Main Genre",
    animeCount: 340,
    description: "Futuristic technology, space exploration, and futuristic concepts.",
    colorBadge: "secondary",
    isActive: true,
  },
  {
    id: "gen-6",
    name: "Romance",
    slug: "romance",
    group: "Main Genre",
    animeCount: 420,
    description: "Love stories, emotional bonds, and relationship growth.",
    colorBadge: "outline",
    isActive: true,
  },
  {
    id: "gen-7",
    name: "Shounen",
    slug: "shounen",
    group: "Demographic",
    animeCount: 410,
    description: "Targeted primarily towards young male audiences.",
    colorBadge: "default",
    isActive: true,
  },
  {
    id: "gen-8",
    name: "Seinen",
    slug: "seinen",
    group: "Demographic",
    animeCount: 290,
    description: "Targeted towards young adult and adult male audiences.",
    colorBadge: "secondary",
    isActive: true,
  },
  {
    id: "gen-9",
    name: "Shoujo",
    slug: "shoujo",
    group: "Demographic",
    animeCount: 180,
    description: "Targeted primarily towards young female audiences.",
    colorBadge: "outline",
    isActive: true,
  },
  {
    id: "gen-10",
    name: "Isekai",
    slug: "isekai",
    group: "Theme",
    animeCount: 310,
    description: "Protagonist transported or reincarnated into a parallel world.",
    colorBadge: "default",
    isActive: true,
  },
  {
    id: "gen-11",
    name: "Mecha",
    slug: "mecha",
    group: "Theme",
    animeCount: 145,
    description: "Giant robotic suits and futuristic mechanical warfare.",
    colorBadge: "secondary",
    isActive: true,
  },
  {
    id: "gen-12",
    name: "Slice of Life",
    slug: "slice-of-life",
    group: "Main Genre",
    animeCount: 360,
    description: "Everyday mundane lives and realistic human experiences.",
    colorBadge: "outline",
    isActive: true,
  },
];
