import type {
  EpisodeItem,
  EpisodeStats,
  ServerNode,
  SubtitleCoverageItem,
} from "./types";

export const MOCK_EPISODES: EpisodeItem[] = [
  {
    id: "ep-001",
    animeId: "a-01",
    animeTitle: "Solo Leveling Season 2: Arise from the Shadow",
    animeSlug: "solo-leveling-season-2",
    episodeNumber: 12,
    title: "Arise, Monarch of Shadows",
    thumbnail: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80",
    duration: "23:45",
    airDate: "2026-03-29",
    status: "published",
    viewsCount: 142800,
    isVip: false,
    servers: [
      {
        id: "srv-101",
        name: "Cloudflare R2 HLS",
        type: "hls",
        quality: "1080p",
        url: "https://cdn.goxstream.tv/hls/sl-s2-ep12/master.m3u8",
        isPrimary: true,
        health: "online",
        latencyMs: 38,
      },
      {
        id: "srv-102",
        name: "BunnyCDN Backup",
        type: "hls",
        quality: "1080p",
        url: "https://bunny.goxstream.tv/sl-s2-ep12/playlist.m3u8",
        isPrimary: false,
        health: "online",
        latencyMs: 72,
      },
      {
        id: "srv-103",
        name: "FastEmbed Mirror",
        type: "embed",
        quality: "720p",
        url: "https://embed.stream/v/sl-s2-ep12",
        isPrimary: false,
        health: "degraded",
        latencyMs: 310,
      },
    ],
    subtitles: [
      { id: "sub-1", language: "Indonesian", label: "Bahasa Indonesia", code: "id", url: "/subs/sl-ep12-id.vtt", isDefault: true, format: "vtt" },
      { id: "sub-2", language: "English", label: "English (Full)", code: "en", url: "/subs/sl-ep12-en.vtt", isDefault: false, format: "vtt" },
      { id: "sub-3", language: "Japanese", label: "日本語", code: "ja", url: "/subs/sl-ep12-ja.vtt", isDefault: false, format: "srt" },
    ],
    audioTracks: [
      { id: "aud-1", language: "Japanese", label: "Japanese (Original Voice)", type: "original", isDefault: true },
      { id: "aud-2", language: "English", label: "English Dub", type: "dub", isDefault: false },
    ],
  },
  {
    id: "ep-002",
    animeId: "a-01",
    animeTitle: "Solo Leveling Season 2: Arise from the Shadow",
    animeSlug: "solo-leveling-season-2",
    episodeNumber: 11,
    title: "A Gathering of S-Rank Hunters",
    thumbnail: "https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80",
    duration: "24:10",
    airDate: "2026-03-22",
    status: "published",
    viewsCount: 198500,
    isVip: false,
    servers: [
      {
        id: "srv-101",
        name: "Cloudflare R2 HLS",
        type: "hls",
        quality: "1080p",
        url: "https://cdn.goxstream.tv/hls/sl-s2-ep11/master.m3u8",
        isPrimary: true,
        health: "online",
        latencyMs: 42,
      },
    ],
    subtitles: [
      { id: "sub-1", language: "Indonesian", label: "Bahasa Indonesia", code: "id", url: "/subs/sl-ep11-id.vtt", isDefault: true, format: "vtt" },
      { id: "sub-2", language: "English", label: "English", code: "en", url: "/subs/sl-ep11-en.vtt", isDefault: false, format: "vtt" },
    ],
    audioTracks: [
      { id: "aud-1", language: "Japanese", label: "Japanese Original", type: "original", isDefault: true },
    ],
  },
  {
    id: "ep-003",
    animeId: "a-02",
    animeTitle: "Demon Slayer: Hashira Training Arc",
    animeSlug: "demon-slayer-hashira-training",
    episodeNumber: 8,
    title: "The Hashira Unite",
    thumbnail: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80",
    duration: "45:00",
    airDate: "2026-03-30",
    status: "scheduled",
    viewsCount: 0,
    isVip: true,
    servers: [
      {
        id: "srv-101",
        name: "Cloudflare R2 HLS",
        type: "hls",
        quality: "1080p",
        url: "https://cdn.goxstream.tv/hls/ds-ep8/master.m3u8",
        isPrimary: true,
        health: "online",
        latencyMs: 35,
      },
    ],
    subtitles: [
      { id: "sub-1", language: "Indonesian", label: "Bahasa Indonesia", code: "id", url: "/subs/ds-ep8-id.vtt", isDefault: true, format: "vtt" },
    ],
    audioTracks: [
      { id: "aud-1", language: "Japanese", label: "Japanese Original", type: "original", isDefault: true },
    ],
  },
  {
    id: "ep-004",
    animeId: "a-03",
    animeTitle: "Jujutsu Kaisen Season 3: Culling Game",
    animeSlug: "jujutsu-kaisen-culling-game",
    episodeNumber: 1,
    title: "The Declaration of War",
    thumbnail: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80",
    duration: "24:00",
    airDate: "2026-04-05",
    status: "draft",
    viewsCount: 0,
    isVip: true,
    servers: [
      {
        id: "srv-104",
        name: "Internal Staging Server",
        type: "mp4",
        quality: "1080p",
        url: "https://staging.goxstream.tv/jjk-ep1.mp4",
        isPrimary: true,
        health: "offline",
        latencyMs: 0,
      },
    ],
    subtitles: [],
    audioTracks: [
      { id: "aud-1", language: "Japanese", label: "Japanese Original", type: "original", isDefault: true },
    ],
  },
  {
    id: "ep-005",
    animeId: "a-04",
    animeTitle: "Frieren: Beyond Journey's End Season 2",
    animeSlug: "frieren-season-2",
    episodeNumber: 3,
    title: "The Northern Lands",
    thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    duration: "23:50",
    airDate: "2026-03-27",
    status: "published",
    viewsCount: 112400,
    isVip: false,
    servers: [
      {
        id: "srv-101",
        name: "Cloudflare R2 HLS",
        type: "hls",
        quality: "1080p",
        url: "https://cdn.goxstream.tv/hls/frieren-ep3/master.m3u8",
        isPrimary: true,
        health: "online",
        latencyMs: 40,
      },
      {
        id: "srv-102",
        name: "BunnyCDN Backup",
        type: "hls",
        quality: "720p",
        url: "https://bunny.goxstream.tv/frieren-ep3/playlist.m3u8",
        isPrimary: false,
        health: "online",
        latencyMs: 65,
      },
    ],
    subtitles: [
      { id: "sub-1", language: "Indonesian", label: "Bahasa Indonesia", code: "id", url: "/subs/frieren-ep3-id.vtt", isDefault: true, format: "vtt" },
      { id: "sub-2", language: "English", label: "English", code: "en", url: "/subs/frieren-ep3-en.vtt", isDefault: false, format: "vtt" },
    ],
    audioTracks: [
      { id: "aud-1", language: "Japanese", label: "Japanese Original", type: "original", isDefault: true },
    ],
  },
];

export const MOCK_EPISODE_STATS: EpisodeStats = {
  totalEpisodes: 8920,
  publishedEpisodes: 8640,
  draftEpisodes: 180,
  serverIssues: 12,
  totalViews: 42800000,
};

export const MOCK_SERVER_NODES: ServerNode[] = [
  {
    id: "srv-node-1",
    name: "Cloudflare R2 Primary Edge",
    region: "Asia Pacific (Singapore)",
    provider: "Cloudflare R2",
    endpoint: "https://cdn-sg.goxstream.tv/hls/",
    status: "online",
    latencyMs: 38,
    activeConnections: 18450,
    bandwidthUsageGbps: 8.4,
    totalCapacityGbps: 20.0,
    isPrimary: true,
  },
  {
    id: "srv-node-2",
    name: "BunnyCDN Secondary Mirror",
    region: "Tokyo / Japan Edge",
    provider: "BunnyCDN",
    endpoint: "https://cdn-tokyo.goxstream.tv/stream/",
    status: "online",
    latencyMs: 65,
    activeConnections: 6200,
    bandwidthUsageGbps: 3.1,
    totalCapacityGbps: 10.0,
    isPrimary: false,
  },
  {
    id: "srv-node-3",
    name: "FastEmbed Embed Proxy",
    region: "US East (N. Virginia)",
    provider: "FastEmbed Network",
    endpoint: "https://embed.stream/api/v1/",
    status: "degraded",
    latencyMs: 290,
    activeConnections: 1400,
    bandwidthUsageGbps: 1.2,
    totalCapacityGbps: 5.0,
    isPrimary: false,
  },
  {
    id: "srv-node-4",
    name: "Internal Transcoder Storage",
    region: "Jakarta Local Server",
    provider: "MinIO Local Cluster",
    endpoint: "http://10.10.40.12:9000/episodes/",
    status: "offline",
    latencyMs: 0,
    activeConnections: 0,
    bandwidthUsageGbps: 0.0,
    totalCapacityGbps: 2.0,
    isPrimary: false,
  },
];

export const MOCK_SUBTITLE_COVERAGE: SubtitleCoverageItem[] = [
  {
    animeId: "a-01",
    animeTitle: "Solo Leveling Season 2: Arise from the Shadow",
    totalEpisodes: 12,
    subtitlesCount: { id: 12, en: 12, ja: 8 },
    missingCount: 4,
  },
  {
    animeId: "a-02",
    animeTitle: "Demon Slayer: Hashira Training Arc",
    totalEpisodes: 8,
    subtitlesCount: { id: 8, en: 8, ja: 8 },
    missingCount: 0,
  },
  {
    animeId: "a-03",
    animeTitle: "Jujutsu Kaisen Season 3: Culling Game",
    totalEpisodes: 1,
    subtitlesCount: { id: 0, en: 0, ja: 0 },
    missingCount: 3,
  },
  {
    animeId: "a-04",
    animeTitle: "Frieren: Beyond Journey's End Season 2",
    totalEpisodes: 3,
    subtitlesCount: { id: 3, en: 3, ja: 2 },
    missingCount: 1,
  },
];
