import type { ReportedComment } from "./types";

export const MOCK_MODERATION_QUEUE: ReportedComment[] = [
  {
    id: "rep-001",
    commentId: "cmt-101",
    commentText: "Gojo dies in episode 14 bro!! Don't watch it haha XD",
    animeTitle: "Jujutsu Kaisen Season 2",
    episodeNumber: 14,
    author: {
      id: "usr-901",
      name: "TrollKing99",
      username: "trollking99",
      avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
    },
    reporter: {
      id: "usr-001",
      name: "Alex Vance",
      username: "ShadowMonarch99",
    },
    reason: "spoiler",
    status: "pending",
    reportedAt: "2026-08-26T10:15:00Z",
    flaggedBySystem: false,
  },
  {
    id: "rep-002",
    commentId: "cmt-102",
    commentText: "Free VIP accounts here! Click link: http://fake-anime-vip.phishing/login",
    animeTitle: "Solo Leveling",
    episodeNumber: 12,
    author: {
      id: "usr-902",
      name: "BotSpammer01",
      username: "botspammer01",
      avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80",
    },
    reporter: {
      id: "usr-002",
      name: "Sarah Jenkins",
      username: "OtakuSensei",
    },
    reason: "spam_link",
    status: "pending",
    reportedAt: "2026-08-26T09:40:00Z",
    flaggedBySystem: true,
  },
  {
    id: "rep-003",
    commentId: "cmt-103",
    commentText: "This anime MC is so trash and anyone who likes this series is an idiot.",
    animeTitle: "Demon Slayer S4",
    episodeNumber: 6,
    author: {
      id: "usr-903",
      name: "AngryRantGuy",
      username: "angryrantguy",
      avatar: "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=150&auto=format&fit=crop&q=80",
    },
    reporter: {
      id: "usr-003",
      name: "Kenji Sato",
      username: "AnimeExplorer",
    },
    reason: "hate_speech",
    status: "pending",
    reportedAt: "2026-08-26T08:20:00Z",
    flaggedBySystem: false,
  },
  {
    id: "rep-004",
    commentId: "cmt-104",
    commentText: "Check out my YouTube channel for episode reactions!!",
    animeTitle: "Frieren: Beyond Journey's End",
    episodeNumber: 24,
    author: {
      id: "usr-904",
      name: "YouTuberSpam",
      username: "youtuberspam",
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    },
    reporter: {
      id: "usr-004",
      name: "Elena Rostova",
      username: "ElenaOtaku",
    },
    reason: "other",
    status: "resolved",
    reportedAt: "2026-08-25T16:00:00Z",
    flaggedBySystem: false,
  },
];
